name: weltreise
repository_url: https://github.com/weltreise-dora-the-explorer/Weltreise_Server.git
reference: main
compose_files:
  - production.docker-compose.yaml

---
name: scotlandyard
repository_url: https://github.com/SE2-S26-Gruppe2-ScotlandYard/ScotlandYard-Server.git
reference: main
compose_files:
  - production.docker-compose.yaml

---
name: saboteur
repository_url: https://github.com/SE2Gruppe3/Saboteur.git
reference: main
compose_files:
  - production.docker-compose.yaml

---
name: monopoly
repository_url: https://github.com/AAU-SE2-Monopoly/aau-se2-backend.git
reference: main
compose_files:
  - production.docker-compose.yaml

---
name: skyjo
repository_url: https://github.com/aause2gruppe5/skyjo_aau26_se2_backend.git
reference: main
compose_files:
  - production.docker-compose.yaml

