# Test deployment
name: grp-0-se2-server-example
repository_url: https://github.com/W3D3/se2-server-example.git
reference: main
compose_files:
  - production.docker-compose.yaml

---
name: grp-4-monopoly-klagenfurt
repository_url: https://github.com/AAU-SE2-Monopoly/aau-se2-backend.git
reference: main
compose_files:
  - production.docker-compose.yaml

